% extractFeatures.m
fs = 50;
windowSec = 1;
N = fs * windowSec;  % 50 samples per window

trainFiles  = {'stationary.csv', 'fidgeting.csv', 'walking.csv', 'running.csv'};
trainLabels = {'stationary',     'fidgeting',     'walking',     'running'};

featuresTable = buildFeatures(trainFiles, trainLabels, N);
disp('Done! featuresTable is ready.');
disp(summary(featuresTable));

function T = buildFeatures(files, labels, N)
    T = table();
    for i = 1:length(files)
        data = readtable(files{i}, 'TextType', 'string');

        % Print what columns were actually found (sanity check)
        fprintf('File: %s  Columns: %s\n', files{i}, strjoin(data.Properties.VariableNames, ', '));

        nWindows = floor(height(data) / N);
        fprintf('  -> %d samples, %d windows\n', height(data), nWindows);

        for w = 1:nWindows
            rows = data((w-1)*N+1 : w*N, :);

            ax = rows.ax; ay = rows.ay; az = rows.az;
            gx = rows.gx; gy = rows.gy; gz = rows.gz;

            % Match column names to your actual header
            heel = rows.heel;
            toe  = rows.toe;

            % --- Derived signals ---
            accMag  = sqrt(ax.^2 + ay.^2 + az.^2);
            gyroMag = sqrt(gx.^2 + gy.^2 + gz.^2);

            % Zero-crossing rate of gyroMag (rhythmicity)
            zcr = sum(diff(sign(gyroMag - mean(gyroMag))) ~= 0) / N;

            % Step events: count heel rising edges above threshold
            % (tune heelThresh by looking at your walking data)
            heelThresh = 1500;
            heelSteps  = sum(diff(double(heel) > heelThresh) > 0);

            % Heel-toe load ratio
            heelToeRatio = mean(heel) / (mean(toe) + 1);

            row = table( ...
                categorical({labels{i}}), ...
                mean(ax), mean(ay), mean(az), ...
                mean(gx), mean(gy), mean(gz), ...
                std(ax),  std(ay),  std(az), ...
                std(gx),  std(gy),  std(gz), ...
                range(ax), range(ay), range(az), ...
                range(gx), range(gy), range(gz), ...
                mean(accMag),  std(accMag),  max(accMag), ...
                mean(gyroMag), std(gyroMag), max(gyroMag), ...
                zcr, ...
                mean(heel), mean(toe), std(heel), std(toe), ...
                max(heel),  max(toe), ...
                heelToeRatio, double(heelSteps) ...
            );

            T = [T; row];
        end
    end

    T.Properties.VariableNames = {'Activity', ...
        'mean_ax','mean_ay','mean_az', ...
        'mean_gx','mean_gy','mean_gz', ...
        'std_ax','std_ay','std_az', ...
        'std_gx','std_gy','std_gz', ...
        'range_ax','range_ay','range_az', ...
        'range_gx','range_gy','range_gz', ...
        'mean_accMag','std_accMag','max_accMag', ...
        'mean_gyroMag','std_gyroMag','max_gyroMag', ...
        'zcr', ...
        'mean_heel','mean_toe','std_heel','std_toe', ...
        'max_heel','max_toe', ...
        'heelToeRatio','heelSteps'};
end